# Main_config.yaml
#Path
RAVAGE_HOME: "/home/koil/src/ravage/"
ARDUPILOT_HOME: "/home/koil/src/ardupilot/"
PX4_HOME: "/home/koil/src/PX4-Autopilot/"

#Waypoint file
WAYPOINT_FILE: "/square_copter.txt"

#Vehicle types
ROVER: "No"
COPTER: "Yes"
SUB: "No"
