# Main_config.yaml
#Path
RAVAGE_HOME: "/mnt/c/Users/jonzd/.vscode/HTML/CS6434/src/ravage/"
ARDUPILOT_HOME: "/mnt/c/Users/jonzd/.vscode/HTML/CS6434/src/ardupilot/"
PX4_HOME: "/mnt/c/Users/jonzd/.vscode/HTML/CS6434/src/PX4-Autopilot/"

#Waypoint file
WAYPOINT_FILE: "/square_copter.txt"

#Vehicle types
ROVER: "No"
COPTER: "Yes"
SUB: "No"
